from __future__ import annotations

from typing import Protocol
from uuid import UUID

from app.domain.entities import Conductor, Usuario, Vehiculo


class VehiculoRepository(Protocol):
    async def crear(self, vehiculo: Vehiculo) -> Vehiculo: ...

    async def obtener_por_id(self, vehiculo_id: UUID) -> Vehiculo | None: ...

    async def obtener_por_id_bloqueado(self, vehiculo_id: UUID) -> Vehiculo | None:
        """Igual que obtener_por_id pero toma un lock de fila (SELECT ... FOR UPDATE)
        para evitar asignaciones concurrentes duplicadas."""
        ...

    async def obtener_por_placa(self, placa: str) -> Vehiculo | None: ...

    async def listar(self, skip: int = 0, limit: int = 100) -> list[Vehiculo]: ...

    async def actualizar(self, vehiculo: Vehiculo) -> Vehiculo: ...

    async def eliminar(self, vehiculo_id: UUID) -> None: ...


class ConductorRepository(Protocol):
    async def crear(self, conductor: Conductor) -> Conductor: ...

    async def obtener_por_id(self, conductor_id: UUID) -> Conductor | None: ...

    async def obtener_por_id_bloqueado(self, conductor_id: UUID) -> Conductor | None:
        """Igual que obtener_por_id pero toma un lock de fila (SELECT ... FOR UPDATE)
        para evitar asignaciones concurrentes duplicadas."""
        ...

    async def obtener_por_licencia(self, licencia: str) -> Conductor | None: ...

    async def listar(self, skip: int = 0, limit: int = 100) -> list[Conductor]: ...

    async def actualizar(self, conductor: Conductor) -> Conductor: ...

    async def eliminar(self, conductor_id: UUID) -> None: ...


class UsuarioRepository(Protocol):
    async def crear(self, usuario: Usuario) -> Usuario: ...

    async def obtener_por_id(self, usuario_id: UUID) -> Usuario | None: ...

    async def obtener_por_email(self, email: str) -> Usuario | None: ...
